// frontend/src/routes/login.tsx
import { useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { sessionAPI } from "@/lib/api";
import { toast } from "sonner";

export const Route = createFileRoute("/login")({
  component: LoginPage,
});

function LoginPage() {
  const navigate = useNavigate();
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!password.trim()) {
      toast.error("Please enter a password");
      return;
    }

    setIsLoading(true);
    try {
      await sessionAPI.login({ password });
      navigate({ to: "/" });
    } catch (error) {
      toast.error("Invalid password");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-background">
      <div className="w-full max-w-sm space-y-6 p-4">
        {/* Logo */}
        <div className="flex flex-col items-center gap-2">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary">
            <span className="text-xl font-bold text-primary-foreground">F</span>
          </div>
          <h1 className="text-2xl font-bold">Fusion</h1>
          <p className="text-sm text-muted-foreground">
            Enter your password to continue
          </p>
        </div>

        {/* Login form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          <Input
            type="password"
            placeholder="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            disabled={isLoading}
            autoFocus
          />
          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? "Signing in..." : "Sign in"}
          </Button>
        </form>
      </div>
    </div>
  );
}

// frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { login } from '$lib/api/login';
	import { toast } from 'svelte-sonner';

	let password = $state('');

	async function handleSubmit(e: Event) {
		e.preventDefault();

		try {
			await login(password);
			await goto('/');
		} catch (e) {
			toast.error((e as Error).message);
		}
	}
</script>

<svelte:head>
	<title>Login</title>
</svelte:head>

<div class="flex h-[100vh] items-center justify-center">
	<form
		onsubmit={handleSubmit}
		class="bg-base-100 border-base-content/10 container flex max-w-[400px] -translate-y-[10vh] flex-col rounded-xl border p-8"
	>
		<h1 class="mb-4 text-center text-2xl font-bold">Login</h1>
		<fieldset class="fieldset">
			<legend class="fieldset-legend">Password</legend>
			<input
				name="password"
				type="password"
				autocomplete="current-password"
				bind:value={password}
				class="input w-full"
			/>
		</fieldset>
		<button type="submit" class="btn btn-primary mt-4 w-full">Login</button>
	</form>
</div>
